const $=id=>document.getElementById(id);let worker,loaded=false,active=false,ctx,stream,source,capture,generation=0,sequence=0,rows=[],events=[],sent=new Map(),resetWait,resetReject,checking=false,recordingMode="mono",endingTimer;const sessionRows=[];
function status(text){$('status').textContent=text;}
function controls(){for(const id of ['mic','demo','file','check'])$(id).disabled=!loaded||active;$('mode').disabled=active;$('stop').disabled=!active||checking;$('load').disabled=loaded;}
function error(message){resetReject?.(Error(message));resetWait=null;resetReject=null;checking=false;stop();status(message);if(!loaded)$('load').disabled=false;}
$('load').onclick=()=>{worker?.terminate();worker=new Worker('./worker.js');$('load').disabled=true;$('progress').hidden=false;status('Checking WebGPU and loading the model…');worker.onmessage=onMessage;worker.onerror=e=>error(e.message||'The model worker stopped. Reload this page.');worker.postMessage({type:'load'});};
function onMessage({data:d}){if(d.type==='progress'){$('progress').value=Math.min(1,d.loaded/d.total);$('download').textContent=`${(d.loaded/1e6).toFixed(0)} / ${(d.total/1e6).toFixed(0)} MB · ${d.label}`;}else if(d.type==='status')status(d.text);else if(d.type==='device')$('device').textContent=`WEBGPU · ${d.vendor||'GPU'}`;else if(d.type==='ready'){loaded=true;$('progress').hidden=true;$('download').textContent='Model ready. Audio is processed locally; model assets may be cached for next time.';status('Ready. Try the spoken example or start your microphone.');controls();}else if(d.type==='reset'){resetWait?.();resetWait=null;resetReject=null;}else if(d.type==='error')error(d.message);else if(d.type==='frame'&&d.generation===generation){const received=performance.now(),lag=received-(sent.get(d.sequence)||received);sent.delete(d.sequence);const row={...d,lagMs:lag};rows.push(row);if(rows.length>75)rows.shift();sessionRows.push(row);if(sessionRows.length>12000)sessionRows.shift();render(row);$('export').disabled=false;}else if(d.type==='check'){$('checkResult').textContent=JSON.stringify(d,null,2);status(d.passed?'Synthetic audio pipeline check passed.':'Synthetic check failed on this device; results may be unreliable.');active=false;checking=false;controls();}}
function modeChanged(){$('speaker2').hidden=$('mode').value==='mono';$('modeHint').textContent=$('mode').value==='mono'?'One-speaker mode listens to the first channel and supplies silence for the other. No retraining or speaker separation.':'Stereo files/devices must contain one speaker per channel. Mixed voices cannot be separated.';draw();}$('mode').onchange=modeChanged;
async function begin(){if(active||!loaded)return false;active=true;controls();recordingMode=$("mode").value;generation++;rows=[];events=[];sessionRows.length=0;sequence=0;sent.clear();$('events').replaceChildren();$('empty').hidden=false;status('Resetting conversation state…');await new Promise((resolve,reject)=>{resetWait=resolve;resetReject=reject;worker.postMessage({type:'reset',generation});});ctx=new AudioContext({sampleRate:16000});await ctx.resume();if(ctx.sampleRate!==16000)throw Error('This browser did not provide 16 kHz audio. Try desktop Chrome.');await ctx.audioWorklet.addModule('./capture.js');capture=new AudioWorkletNode(ctx,'pardon-capture',{numberOfInputs:1,numberOfOutputs:1,outputChannelCount:[1],channelCount:2,channelCountMode:'explicit'});capture.connect(ctx.destination);capture.port.onmessage=({data:pcm})=>{if(!active)return;if($('mode').value==='mono')pcm[1].fill(0);const n=sequence++;sent.set(n,performance.now());worker.postMessage({type:'audio',generation,sequence:n,pcm},pcm.map(x=>x.buffer));};return true;}
function stop(){clearTimeout(endingTimer);active=false;capture?.port.postMessage('stop');try{source?.stop();}catch{}source?.disconnect();capture?.disconnect();for(const track of stream?.getTracks()||[])track.stop();stream=null;ctx?.close();ctx=null;controls();}
$('stop').onclick=()=>{stop();status('Stopped. Start again for a fresh conversation.');};
$('mic').onclick=async()=>{try{if(!await begin())return;stream=await navigator.mediaDevices.getUserMedia({audio:{sampleRate:16000,channelCount:$('mode').value==='mono'?1:2,echoCancellation:false,noiseSuppression:false,autoGainControl:false}});if(!active){stream.getTracks().forEach(t=>t.stop());return;}if($('mode').value==='stereo'&&stream.getAudioTracks()[0].getSettings().channelCount!==2)throw Error('This microphone did not provide two channels. Choose One speaker mode.');source=ctx.createMediaStreamSource(stream);source.connect(capture);status('Listening. Speak, pause, and watch for a finished turn.');}catch(e){error(e.name==='NotAllowedError'?'Microphone access was denied. Allow it in your browser, or use the example.':e.message);}};
async function play(buffer,label){try{if(!await begin())return;const decoded=await ctx.decodeAudioData(buffer);if($('mode').value==='stereo'&&decoded.numberOfChannels<2)throw Error('This file has one channel. Choose One speaker mode.');source=ctx.createBufferSource();source.buffer=decoded;source.connect(capture);source.connect(ctx.destination);source.onended=()=>{if(active){status('Finishing queued audio…');const finish=()=>{if(!active)return;if(sent.size){endingTimer=setTimeout(finish,200);return;}stop();status('Example finished. Start your microphone to try it yourself.');};endingTimer=setTimeout(finish,250);}};source.start();status(label+' · playing and detecting in real time');}catch(e){error(e.message);}}
$('demo').onclick=async()=>{try{if($('mode').value==='stereo'){$('mode').value='mono';modeChanged();}status('Loading the synthetic spoken example…');const r=await fetch('./assets/demo.wav');if(!r.ok)throw Error('Could not load the example.');await play(await r.arrayBuffer(),'Synthetic spoken example');}catch(e){error(e.message);}};
$('file').onchange=async e=>{const file=e.target.files?.[0];if(file)await play(await file.arrayBuffer(),file.name);e.target.value='';};
$('check').onclick=()=>{checking=true;active=true;controls();$('checkResult').textContent='Checking deterministic synthetic audio against the CPU reference…';worker.postMessage({type:'check'});};
function render(row){const mono=$('mode').value==='mono';for(let c=0;c<(mono?1:2);c++){const n=c+1,p=row.probabilities[c],v=row.vad[c];$('score'+n).textContent=Math.round(p*100)+'%';$('bar'+n).style.width=p*100+'%';$('vad'+n).textContent=Math.round(v*100)+'%';$('state'+n).textContent=v>=.5?'Speaking':'Quiet';}$('compute').textContent=Math.round(row.computeMs)+' ms';$('lag').textContent=Math.round(row.lagMs)+' ms';$('audioTime').textContent=row.time.toFixed(2)+' s';$('pace').textContent=row.queue>1?`${row.queue} audio blocks queued. The device is falling behind.`:'Decisions every 160 ms · recurrent state kept on the GPU.';for(const event of row.events){if(mono&&event.speaker!==1)continue;events.push({...event,lagMs:row.lagMs});$('empty').hidden=true;const li=document.createElement('li'),time=document.createElement('time'),label=document.createElement('b'),score=document.createElement('span');time.textContent=event.time.toFixed(2)+' s';label.textContent=`Speaker ${event.speaker} · turn complete`;score.textContent=Math.round(event.score*100)+'%';li.append(time,label,score);$('events').prepend(li);while($('events').children.length>20)$('events').lastElementChild.remove();const card=$('speaker'+event.speaker);card.classList.remove('flash');void card.offsetWidth;card.classList.add('flash');$('state'+event.speaker).textContent='Turn complete';}draw();}
function draw(){const canvas=$('chart'),dpr=devicePixelRatio||1,w=canvas.clientWidth,h=canvas.clientHeight;canvas.width=w*dpr;canvas.height=h*dpr;const g=canvas.getContext('2d');g.scale(dpr,dpr);g.clearRect(0,0,w,h);g.strokeStyle='#e8eee6';for(let i=0;i<5;i++){g.beginPath();g.moveTo(0,10+i*(h-20)/4);g.lineTo(w,10+i*(h-20)/4);g.stroke();}g.setLineDash([4,5]);g.strokeStyle='#bbcab9';g.beginPath();g.moveTo(0,10+(1-.8214424509124978)*(h-20));g.lineTo(w,10+(1-.8214424509124978)*(h-20));g.stroke();g.setLineDash([]);for(let c=0;c<($('mode').value==='mono'?1:2);c++)for(const key of ['vad','probabilities']){g.strokeStyle=key==='vad'?'#b9c9b8':c?'#bd8560':'#3d976e';g.lineWidth=key==='vad'?1:2;g.beginPath();rows.forEach((r,i)=>{const x=i/74*w,y=10+(1-r[key][c])*(h-20);i?g.lineTo(x,y):g.moveTo(x,y);});g.stroke();}}
$('export').onclick=()=>{const blob=new Blob([JSON.stringify({mode:recordingMode,model:'continued-full17-fp32',audioUploaded:false,threshold:.8214424509124978,events,frames:sessionRows},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='pardon-turn-session.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};window.addEventListener('resize',draw);window.addEventListener('pagehide',()=>{stop();worker?.terminate();});draw();
